# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'threshdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class analysisUi_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(278, 239)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.redThresh = QtWidgets.QLineEdit(Dialog)
        self.redThresh.setAlignment(QtCore.Qt.AlignCenter)
        self.redThresh.setObjectName("redThresh")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.redThresh)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.blueThresh = QtWidgets.QLineEdit(Dialog)
        self.blueThresh.setAlignment(QtCore.Qt.AlignCenter)
        self.blueThresh.setObjectName("blueThresh")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.blueThresh)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.redPeakThresh = QtWidgets.QLineEdit(Dialog)
        self.redPeakThresh.setAlignment(QtCore.Qt.AlignCenter)
        self.redPeakThresh.setObjectName("redPeakThresh")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.redPeakThresh)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.bluePeakThresh = QtWidgets.QLineEdit(Dialog)
        self.bluePeakThresh.setAlignment(QtCore.Qt.AlignCenter)
        self.bluePeakThresh.setObjectName("bluePeakThresh")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bluePeakThresh)
        self.gridLayout.addLayout(self.formLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Threshold Values:"))
        self.label_3.setText(_translate("Dialog", "Reds:"))
        self.redThresh.setText(_translate("Dialog", "1"))
        self.label_5.setText(_translate("Dialog", "Blues:"))
        self.blueThresh.setText(_translate("Dialog", "1"))
        self.label_7.setText(_translate("Dialog", "Inter-Peak Threshold:"))
        self.label_4.setText(_translate("Dialog", "Reds:"))
        self.redPeakThresh.setText(_translate("Dialog", "1"))
        self.label_6.setText(_translate("Dialog", "Blues:"))
        self.bluePeakThresh.setText(_translate("Dialog", "1"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.okButton.setText(_translate("Dialog", "OK"))

